name: Daily Scraper

on:
  schedule:
    - cron: "0 3 * * *"  # UTCの3時 → 日本時間で12時
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send result to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content":"✅ Scraper finished! events.json updated."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
